name: Upload artifact

on:
  pull_request:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
      - name: Build
        run: scons version=${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: add-on
          path: "*.nvda-addon"
          overwrite: true
